### PR TITLE
optimize networking

### LINKED ISSUE #41: optimizing networking in qubic-cli
Currently many functions in `qubic-cli` use `receiveDataAll` (connection.cpp) to receive all bytes (getting blocked at `recv` for 2 seconds) from nodes and then process.
This behavior must be changed for further development, as well as making better example for community devs to implement their software.
Since all queries to nodes have predefined size, we should **replace** `receiveDataAll` with `receivePacketWithHeaderAs` or `receivePacketAs` or `getLatestVectorPacketAs` (Feel free to rename them if needed)

This task also help new dev getting started with all available API from core node.

### PR DESCRIPTION
**Pull request by Franziska-Mueller**
closes #41

### CODE REVIEW

**Comment by philippwerner** [comment]
Well done so far, thanks.

I have recently merged https://github.com/qubic/qubic-cli/pull/32
Can you please merge main to your branch, review qearn.cpp, and improve this new part as well?

**Comment by philippwerner** [comment]
I now have also merged https://github.com/qubic/qubic-cli/pull/43 to main.
Can you please merge main to your branch, review qearn.cpp and qvault.cpp, and improve these new parts as well?

**Comment by Franziska-Mueller** [comment]
I added the network optimizations to QVAULT.cpp and qearn.cpp.
I had to move some of the structs to the headers to enable template instantiations in connection.cpp.

**Review by philippwerner — APPROVED** [review]
All good, I will merge now.

**Pull request merged**
